name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y pkg-config libzstd-dev build-essential autoconf automake libtool
      - name: Build (Makefile)
        run: make
      - name: Build (Autotools)
        run: |
          ./autogen.sh
          ./configure
          make
